-- ============================================================
-- CUSTOMER & REVENUE INTELLIGENCE PLATFORM
-- REVENUE ANALYSIS
-- ============================================================

-- ------------------------------------------------------------
-- 1. TOTAL DELIVERED PRODUCT REVENUE
-- Business Question:
-- How much product revenue was generated by delivered orders?
--
-- Definition:
-- Product Revenue = SUM(order_items.price)
-- Only delivered orders are included.
-- Freight is analyzed separately.
-- ------------------------------------------------------------

SELECT
    ROUND(SUM(oi.price)::numeric, 2) AS total_product_revenue
FROM orders AS o

INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id

WHERE o.order_status = 'delivered';

-- ------------------------------------------------------------
-- 2. PRODUCT REVENUE AND FREIGHT
-- Business Question:
-- How much value comes from products versus freight charges?
-- ------------------------------------------------------------

SELECT
    ROUND(SUM(oi.price)::numeric, 2)
        AS product_revenue,

    ROUND(SUM(oi.freight_value)::numeric, 2)
        AS freight_value,

    ROUND(SUM(oi.price + oi.freight_value)::numeric, 2)
        AS total_customer_value

FROM orders AS o

INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id

WHERE o.order_status = 'delivered';

-- ------------------------------------------------------------
-- 3. DELIVERED ORDERS
-- Business Question:
-- How many orders were successfully delivered?
-- ------------------------------------------------------------

SELECT
    COUNT(DISTINCT order_id) AS delivered_orders
FROM orders
WHERE order_status = 'delivered';

-- ------------------------------------------------------------
-- 4. AVERAGE ORDER VALUE (AOV)
-- Business Question:
-- What is the average product revenue generated per delivered
-- order?
-- ------------------------------------------------------------

SELECT
    ROUND(
        (
            SUM(oi.price)
            /
            COUNT(DISTINCT o.order_id)
        )::numeric,
        2
    ) AS average_order_value

FROM orders AS o

INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id

WHERE o.order_status = 'delivered';

-- ------------------------------------------------------------
-- 5. MONTHLY PRODUCT REVENUE
-- Business Question:
-- How has delivered product revenue changed over time?
-- ------------------------------------------------------------

SELECT
    DATE_TRUNC(
        'month',
        o.order_purchase_timestamp::timestamp
    ) AS month,

    ROUND(
        SUM(oi.price)::numeric,
        2
    ) AS product_revenue

FROM orders AS o

INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id

WHERE o.order_status = 'delivered'

GROUP BY
    DATE_TRUNC(
        'month',
        o.order_purchase_timestamp::timestamp
    )

ORDER BY month;

-- ------------------------------------------------------------
-- 6. ORDER ACTIVITY BY MONTH
-- Purpose:
-- Identify potentially incomplete months before interpreting
-- monthly revenue trends.
-- ------------------------------------------------------------

SELECT
    DATE_TRUNC(
        'month',
        order_purchase_timestamp::timestamp
    ) AS month,

    MIN(order_purchase_timestamp::timestamp)
        AS first_order_in_month,

    MAX(order_purchase_timestamp::timestamp)
        AS last_order_in_month,

    COUNT(*) AS orders

FROM orders

GROUP BY
    DATE_TRUNC(
        'month',
        order_purchase_timestamp::timestamp
    )

ORDER BY month;

-- ------------------------------------------------------------
-- 7. MONTHLY AVERAGE ORDER VALUE
-- Business Question:
-- How has average order value changed over time?
-- ------------------------------------------------------------

SELECT
    DATE_TRUNC(
        'month',
        o.order_purchase_timestamp::timestamp
    ) AS month,

    COUNT(DISTINCT o.order_id)
        AS delivered_orders,

    ROUND(
        SUM(oi.price)::numeric,
        2
    ) AS product_revenue,

    ROUND(
        (
            SUM(oi.price)
            /
            COUNT(DISTINCT o.order_id)
        )::numeric,
        2
    ) AS average_order_value

FROM orders AS o

INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id

WHERE o.order_status = 'delivered'

GROUP BY
    DATE_TRUNC(
        'month',
        o.order_purchase_timestamp::timestamp
    )

ORDER BY month;

-- ------------------------------------------------------------
-- 8. MONTH-OVER-MONTH REVENUE GROWTH
-- Business Question:
-- How quickly is product revenue growing or declining compared
-- with the previous month?
-- ------------------------------------------------------------

WITH monthly_revenue AS (

    SELECT
        DATE_TRUNC(
            'month',
            o.order_purchase_timestamp::timestamp
        ) AS month,

        SUM(oi.price) AS revenue

    FROM orders AS o

    INNER JOIN order_items AS oi
        ON o.order_id = oi.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY
        DATE_TRUNC(
            'month',
            o.order_purchase_timestamp::timestamp
        )
),

revenue_with_previous_month AS (

    SELECT
        month,
        revenue,

        LAG(revenue) OVER (
            ORDER BY month
        ) AS previous_month_revenue

    FROM monthly_revenue
)

SELECT
    month,

    ROUND(
        revenue::numeric,
        2
    ) AS revenue,

    ROUND(
        previous_month_revenue::numeric,
        2
    ) AS previous_month_revenue,

    ROUND(
        (
            (
                revenue - previous_month_revenue
            )
            /
            NULLIF(previous_month_revenue, 0)
            * 100
        )::numeric,
        2
    ) AS month_over_month_growth_pct

FROM revenue_with_previous_month

ORDER BY month;

-- ------------------------------------------------------------
-- 9. EXECUTIVE REVENUE KPI SUMMARY
-- Purpose:
-- Produce a compact summary of the core revenue KPIs used
-- throughout the project.
-- ------------------------------------------------------------

SELECT
    COUNT(DISTINCT o.order_id)
        AS delivered_orders,

    ROUND(
        SUM(oi.price)::numeric,
        2
    ) AS product_revenue,

    ROUND(
        SUM(oi.freight_value)::numeric,
        2
    ) AS freight_value,

    ROUND(
        SUM(oi.price + oi.freight_value)::numeric,
        2
    ) AS total_customer_value,

    ROUND(
        (
            SUM(oi.price)
            /
            COUNT(DISTINCT o.order_id)
        )::numeric,
        2
    ) AS average_order_value

FROM orders AS o

INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id

WHERE o.order_status = 'delivered'; 

96478	13221498.11	2198275.64	15419773.75	137.04

-- ------------------------------------------------------------
-- 10. TOP REVENUE MONTHS
-- Purpose:
-- Identify the strongest months by delivered product revenue.
-- ------------------------------------------------------------

SELECT
    DATE_TRUNC(
        'month',
        o.order_purchase_timestamp::timestamp
    ) AS month,

    COUNT(DISTINCT o.order_id)
        AS delivered_orders,

    ROUND(
        SUM(oi.price)::numeric,
        2
    ) AS product_revenue

FROM orders AS o

INNER JOIN order_items AS oi
    ON o.order_id = oi.order_id

WHERE o.order_status = 'delivered'

GROUP BY
    DATE_TRUNC(
        'month',
        o.order_purchase_timestamp::timestamp
    )

ORDER BY product_revenue DESC

LIMIT 10;

"2017-11-01 00:00:00"	7289	987765.37
"2018-05-01 00:00:00"	6749	977544.69
"2018-04-01 00:00:00"	6798	973534.09
"2018-03-01 00:00:00"	7003	953356.25
"2018-01-01 00:00:00"	7069	924645.00
"2018-07-01 00:00:00"	6159	867953.46
"2018-06-01 00:00:00"	6099	856077.86
"2018-08-01 00:00:00"	6351	838576.64
"2018-02-01 00:00:00"	6555	826437.13
"2017-12-01 00:00:00"	5513	726033.19

